version: '3.9'
services:
  postgres-auth-service:
    image: postgres:15.2-alpine3.17
    env_file:
      - env/postgres-auth-service.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-auth-service:/data/postgres-auth-service
volumes:
  postgres-auth-service: