server:
  port: 8080

spring:
  profiles:
    active: local
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ${client-id}
            client-secret: ${client-secret}
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
jwt:
  tokenSecret: ${token-secret}
  tokenExpirationMsec: 3600000
