version: '3.9'
services:
  postgres-user-management-service:
    image: postgres:15.2-alpine3.17
    env_file:
      - env/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-user-management-service:/data/postgres-user-management-service
volumes:
  postgres-user-management-service: