spring:
  cloud:
    gateway:
      routes:
        - id: test-endpoint
          uri: http://localhost:8090
          predicates:
            - Path=/test/**
token:
  authServerUri: ${AUTH_SERVER_URI:http://localhost:8090/validtoken}