news-api-key: "5d93c657960d453b8ca265fd4be4cbc8"

mongo:
  hostname: "[::1]"
  port: 27018
  databaseName: articles

spring:
  data:
    mongodb:
      uri: mongodb://${mongo.hostname}:${mongo.port}/${mongo.databaseName}

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.data: DEBUG